version: '2'

services:
  functions-visualizer:
    build:
      args:
        output: ${DOCKER_BUILD_OUTPUT}
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
