version: '2'

services:
  functions-visualizer:
    image: functions-visualizer:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    volumes:
      - ./VisualizerWebApp-NetCore:/app
      - ~/.nuget/packages:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      - "com.microsoft.visualstudio.targetoperatingsystem=linux"
